name: Notify release

on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron: '30 8 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: nearform/github-action-notify-release@v1
